### PR TITLE
fixing issue with upload documents

### PR DESCRIPTION
**Pull request by kdcllc**
#55 resolving the issue with missing registration for the `DocumentAnalysisClient` and also updated version of `gpt-4` deployment.

### CODE REVIEW

**Comment by kdcllc** [comment]
> @kdcllc please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree [company="King David Consulting LLC"]

**Comment by kdcllc** [comment]
@microsoft-github-policy-service agree company="King David Consulting LLC"

**Comment by kdcllc** [comment]
@microsoft-github-policy-service agree

**Comment by MarcoABCardoso** [comment]
Hello @kdcllc!

Thank you for submitting a pull request. I have faced this issue before and believe it makes sense to address it like you have.
I'm just validating the contents - we might want to account for the possibility of overriding MSI authentication with an API key (like other services) and review the corresponding infrastructure deployment.

Was the issue you faced a 401/403 error when accessing Document Intelligence? I want to make sure we address your original issue. 

I'll propose a few changes between today and tomorrow.

**Comment by aaronba** [comment]
This is a great fix.
There is another bug in SemanticKernelBot.cs (line 110) where the enablement of the Wikipedia plugin is not checked against the App Settings

Should be:
if (_useWikipedia != false) kernel.ImportPluginFromObject(new WikipediaPlugin(conversationData, turnContext), "WikipediaPlugin");

**Comment by kdcllc** [comment]
@aaronba I can create another pull request for that? Any thoughts @MarcoABCardoso?

**Comment by MarcoABCardoso** [comment]
@aaronba You're absolutely right! This has just been included.
Thanks again for the valuable feedback.

**Pull request closed without merging**
